Update Dockerfile

diff --git a/front-end-nextjs/Dockerfile b/front-end-nextjs/Dockerfile
--- a/front-end-nextjs/Dockerfile
+++ b/front-end-nextjs/Dockerfile
@@ -1,42 +1,26 @@
-# Build stage
-FROM node:18-alpine as base
+# frontend dockerfile
+
+FROM node:18-alpine AS base
 
 WORKDIR /app
 
-COPY package*.json ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 
-RUN npm install
+RUN \
+
+if [ -f yarn.lock ]; then yarn -frozen-lockfile; \
+
+elif [ -f package-lock.json ]; then npm ci; \
+
+elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+ 
+else echo "Lockfile not found." && exit 1; \
+fi
 
 COPY . .
 
-RUN mkdir .next
-
-# Run Stage
-FROM node:18-alpine
-
-WORKDIR /app
-
-# Define a custom UID
-ARG UID=10001
-
-# Create a non-root user with the specified UID
-RUN adduser \
-    --disabled-password \
-    --home "/nonexistent" \
-    --shell "/sbin/nologin" \
-    --no-create-home \
-    --uid "${UID}" \
-    nextjs-user
-
-# Create the /app directory and set ownership
-#RUN mkdir -p /app && chown nextjs-user:nextjs-user /app
-
-# Copy built application from the build stage
-COPY --from=base --chown=nextjs-user:nextjs-user /app /app
-# Switch to the non-root user
-USER nextjs-user
+RUN npm run build
 
 EXPOSE 3000
 
-# Start the application
-CMD ["npm", "run", "dev"]
+CMD ["npm", "start"]
